// Generated by CoffeeScript 1.10.0
(function() {
  var byWdId, k, lang, v, wd;

  lang = require('./lang.json');

  byWdId = {};

  for (k in lang) {
    v = lang[k];
    wd = v.wd;
    byWdId[wd] = v;
  }

  module.exports = {
    byCode: lang,
    byWdId: byWdId
  };

}).call(this);
